print("Please fill in the blanks below:")
print("___(name)___'s favorite food is ____(food)____.")
name = input("Please type a name: ")
food = input("Please type a food: ")
print("%s's favorite food is %s." %(name, food))